language: rust

sudo: false

notifications:
    email: false

branches:
    only: master

rust:
    - nightly
    - beta
    - stable

script:
    - cargo build --verbose
    - cargo test  --verbose
    - cargo build --verbose --all-features
    - cargo test  --verbose --all-features
    - [ $TRAVIS_RUST_VERSION != nightly ] || cargo build --verbose --no-default-features
    - [ $TRAVIS_RUST_VERSION != nightly ] || cargo test  --verbose --no-default-features
